[package]
name = "schemamama_rusqlite"
version = "0.18.0"
authors = ["Chris Dawes <cmsd2@cantab.net>"]
description = "Rusqlite SQLite3 adapter for the Schemamama migration system"
readme = "README.md"
keywords = ["schemamama", "database", "migration", "sqlite", "rusqlite"]
license = "MIT/Apache-2.0"
repository = "https://github.com/cmsd2/schemamama_rusqlite"
documentation = "https://docs.rs/schemamama_rusqlite"
edition = "2018"

[dependencies]
schemamama = "0.3.0"
rusqlite = ">=0.28, <0.41"
log = "0.4.13"
thiserror = "1.0.25"

[dev-dependencies]
env_logger = "~0.11.0"

[features]
unstable = []
